[tool.poetry]
name = "wikillm"
version = "0.1.0"
description = ""
authors = ["Lara Mohan", "Rohan Pandey"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
